import { getIssuesByStatus, getUsers, assignIssue, addComment } from "./jira-service"
import { getRepositoryStructure, getFileContent, createBranch, createFile, createPullRequest } from "./github-service"
import { analyzeTask, generateBlueprintCode } from "./gemini-service"

interface AgentResult {
  issueKey: string
  taskName: string
  status: "completed" | "assigned" | "failed"
  details: {
    branchName?: string
    prUrl?: string
    assignedTo?: string
    reason?: string
    error?: string
  }
}

export async function runAgent(): Promise<AgentResult[]> {
  const results: AgentResult[] = []

  try {
    console.log("[v0] Starting agent...")

    // Step 1: Get issues in "EN CURSO"
    const inProgressIssues = await getIssuesByStatus("In Progress")
    console.log(`[v0] Found ${inProgressIssues.length} issues in progress`)

    // Step 2: Get repository structure to analyze existing blueprints
    const repoStructure = await getRepositoryStructure()
    console.log(`[v0] Repository structure loaded`)

    // Step 3: Get existing blueprint code for context
    let existingCode = ""
    try {
      existingCode = (await getFileContent("scaffolders/blueprints/user-blueprint.ts")) || ""
    } catch (e) {
      console.log("[v0] Could not read existing blueprints")
    }

    // Step 4: Process each issue
    for (const issue of inProgressIssues) {
      const issueKey = issue.key
      const taskName = issue.fields.summary
      const taskDescription = issue.fields.description || ""

      console.log(`[v0] Processing issue: ${issueKey} - ${taskName}`)

      try {
        // Step 5: Analyze with Gemini
        const analysis = await analyzeTask(taskDescription, existingCode)
        console.log(`[v0] Analysis result:`, analysis)

        if (analysis.canImplement) {
          // Step 6a: Generate blueprint code
          const blueprintCode = await generateBlueprintCode(
            taskDescription,
            analysis.blueprintName || taskName.replace(/\s+/g, ""),
            analysis.suggestedFields || [],
          )

          // Step 6b: Create branch
          const branchName = `feat/blueprint-${taskName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`

          await createBranch(branchName)
          console.log(`[v0] Branch created: ${branchName}`)

          // Step 6c: Create blueprint file
          const blueprintFileName = `${taskName.toLowerCase().replace(/\s+/g, "-")}-blueprint.ts`
          const filePath = `scaffolders/blueprints/${blueprintFileName}`

          await createFile(filePath, blueprintCode, branchName, `feat: Add ${taskName} blueprint`)

          console.log(`[v0] Blueprint file created at ${filePath}`)

          // Step 6d: Create Pull Request
          const prResponse = await createPullRequest(
            `[AGENT] Add ${taskName} Blueprint`,
            `This PR automatically adds a new blueprint for: ${taskName}\n\nGenerated by: Blueprint Agent\nDifficulty: ${analysis.difficulty}\nRequired APIs: ${analysis.requiredAPIs.join(", ")}`,
            branchName,
          )

          console.log(`[v0] PR created: ${prResponse.html_url}`)

          // Step 6e: Add comment to Jira
          await addComment(
            issueKey,
            `Agent completed this task!\n\nBranch: ${branchName}\nPR: ${prResponse.html_url}\n\nThe blueprint has been generated and is ready for review.`,
          )

          results.push({
            issueKey,
            taskName,
            status: "completed",
            details: {
              branchName,
              prUrl: prResponse.html_url,
            },
          })
        } else {
          // Step 7: Cannot implement - assign to developer
          const users = await getUsers()

          // Find best match based on suggested developer type
          const matchedUser =
            users.find(
              (u: any) =>
                analysis.suggestedDeveloper && u.displayName.toLowerCase().includes(analysis.suggestedDeveloper),
            ) || users[0]

          if (matchedUser) {
            await assignIssue(issueKey, matchedUser.accountId)

            await addComment(
              issueKey,
              `Agent Analysis: This task requires ${
                analysis.missingResources.length > 0
                  ? `the following resources: ${analysis.missingResources.join(", ")}`
                  : "additional considerations"
              }.\n\nAssigned to: ${matchedUser.displayName}\n\nReason: ${analysis.reasoning}`,
            )

            results.push({
              issueKey,
              taskName,
              status: "assigned",
              details: {
                assignedTo: matchedUser.displayName,
                reason: analysis.reasoning,
              },
            })
          }
        }
      } catch (error) {
        console.error(`[v0] Error processing issue ${issueKey}:`, error)

        results.push({
          issueKey,
          taskName,
          status: "failed",
          details: {
            error: error instanceof Error ? error.message : "Unknown error",
          },
        })
      }
    }

    return results
  } catch (error) {
    console.error("[v0] Agent error:", error)
    throw error
  }
}
